# Generated by Django 4.2.3 on 2023-07-12 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_slug', models.CharField(max_length=128)),
                ('ticker', models.CharField(max_length=15)),
                ('asset_type', models.CharField(choices=[('etf', 'ETF'), ('cryptocurrency', 'Cryptocurrency'), ('stock', 'Stock'), ('commodity', 'Commodity'), ('future', 'Future')], default='stock', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicity', models.CharField(choices=[('daily', 'Daily Candle'), ('weekly', 'Weekly Candle'), ('monthly', 'Monthly Candle')], default='daily', max_length=30)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=10)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('candle_datetime', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
            ],
        ),
    ]
