version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
  strategy-simulator:
    build:
      context: strategy_simulator/
    ports:
      - "${STRATEGY_SIMULATOR_PORT}:${STRATEGY_SIMULATOR_PORT}"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${STRATEGY_SIMULATOR_PORT}"
    volumes:
      - ./strategy_simulator:/home/app
    depends_on:
      - db
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"

volumes:
  pgdata: