version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
  strategy-simulator:
    build:
      context: strategy_simulator/
    ports:
      - "${STRATEGY_SIMULATOR_PORT}:${STRATEGY_SIMULATOR_PORT}"
    command: sh -c "python manage.py migrate && python manage.py runserver ${STRATEGY_SIMULATOR_HOST}:${STRATEGY_SIMULATOR_PORT}"
    volumes:
      - ./strategy_simulator:/home/app
    depends_on:
      - db
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
  strategy-simulator-jupyter:
    build:
      context: strategy_simulator/
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
    command: sh -c "python manage.py migrate && jupyter lab --allow-root --ip=${JUPYTER_HOST} --port=${JUPYTER_PORT}"
    volumes:
      - ./strategy_simulator:/home/app
      - ./strategy_simulator/notebooks/startup.py:/root/.ipython/profile_default/startup/startup.py
    depends_on:
      - db
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      JUPYTER_PORT: "${JUPYTER_PORT}"
      JUPYTER_HOST: "${JUPYTER_HOST}"
      SETTING_FILE_NAME: "settings_dev"

volumes:
  pgdata: